apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tax-calculator-run-
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: repo-url
      value: "https://github.com/USERNAME/tax-calculator.git"
    - name: branch
      value: "main"
    - name: image-name
      value: "us.icr.io/sn-labs-USERNAME/tax-calculator:latest"
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipeline-pvc
